blank_issues_enabled: true
contact_links:
  - name: Contributing guide
    url: https://github.com/DinisMiranda/self_improvement/blob/main/CONTRIBUTING.md
    about: How to contribute with suggestions or PRs
